### PR TITLE
CLI unchecked_clear

### PR DESCRIPTION
**Pull request by SergiySW**
CLI "unchecked_clear" and optional unchecked_clear for "vacuum" & "snapshot"

### CODE REVIEW

**Comment by argakiig** [comment]
LGTM

**Comment by PlasmaPower** [comment]
This only works with `--vacuum` or `--snapshot` right? Why?

**Comment by PlasmaPower** [comment]
Also, if we're going to keep it that way, we should warn/error if it's used without those options.

**Comment by SergiySW** [comment]
No, it also works separate

**Comment by PlasmaPower** [comment]
Oh, yeah I missed that.

**Pull request merged**
