### PR TITLE
RPC refactoring

### PR DESCRIPTION
**Pull request by cryptocode**
Part of https://github.com/nanocurrency/raiblocks/issues/1112

This is just moving things around, should be low risk.

There's a separate rpc lib with handler source files for the major RPC action categories.

### CODE REVIEW

**Comment by cryptocode** [comment]
#1038 is in the same category

**Comment by rotilho** [comment]
Does it fix https://github.com/nanocurrency/raiblocks/issues/896?

**Comment by cryptocode** [comment]
@rotilho This PR doesn't fix any bugs, it's just a refactoring to split the source into smaller files and a separate cmake subdir.

**Comment by cryptocode** [comment]
Anything touching RPC will break this PR, so I'll await rebasing until we decide if this is something we wanna merge.

**Comment by cryptocode** [comment]
I wanna redo this with a few manageable PRs, e.g. do the rpc-as-a-lib-project first, the handler split-up next etc.

**Pull request closed without merging**
