### PR TITLE
Fix several core_test issues

### PR DESCRIPTION
**Pull request by SergiySW**

### CODE REVIEW

**Comment by PlasmaPower** [comment]
We still have the occasional crash on node shutdown, right?

**Comment by PlasmaPower** [comment]
Two tests failing in this PR's latest Travis run:
```
[ RUN      ] network.send_valid_publish
/workspace/rai/core_test/network.cpp:242: Failure
Expected: (latest2) != (latest3), actual: 32-byte object <04-27 0D-7F 11-C4 B2-B4 72-F2 85-4C 5A-59 F2-A7 E8-42 26-CE 9E-D7 99-DE 75-74 4B-D7 D8-5F C9-D9> vs 32-byte object <04-27 0D-7F 11-C4 B2-B4 72-F2 85-4C 5A-59 F2-A7 E8-42 26-CE 9E-D7 99-DE 75-74 4B-D7 D8-5F C9-D9>
[  FAILED  ] network.send_valid_publish (61 ms)
[ RUN      ] node.fork_pre_confirm
/workspace/rai/core_test/node.cpp:1072: Failure
Expected: (iterations) < (400), actual: 400 vs 400
[  FAILED  ] node.fork_pre_confirm (238 ms)
```

**Comment by SergiySW** [comment]
Which is wondering me why it's not failed in multiple runs for me. I'll check with Ubuntu Clang

**Comment by SergiySW** [comment]
It's failing only witn Debug build

**Comment by PlasmaPower** [comment]
`system.generate_send_new` times out on my system (ledger.cpp line 640) and then the test suite hangs.

**Comment by PlasmaPower** [comment]
Should we merge this and require core_test to pass in Travis? It seems to be consistent there now.

**Comment by SergiySW** [comment]
But failed on your system with system.generate_send_new ?

**Comment by PlasmaPower** [comment]
Yes, it consistently fails there on my system. I don't know why. I'll do more investigation later, but it doesn't appear to occur in Travis.

**Comment by PlasmaPower** [comment]
That issue was fixed in https://github.com/nanocurrency/raiblocks/pull/967

**Pull request merged**
