### PR TITLE
If there were more than <announcement_long> announcements, broadcast …

### PR DESCRIPTION
**Pull request by SergiySW**
…confirm request to all known peers

### CODE REVIEW

**Comment by SergiySW** [comment]
Since often issue is not enough observed representatives

**Comment by PlasmaPower** [comment]
This seems like a really bad idea. How about just speeding up rep crawler?

**Comment by SergiySW** [comment]
If it can help. There are only about 350 peers now, but sometimes rep_crawler cannot find enough representatives for thousands of seconds while it should check about 2.5 peers every second

**Comment by SergiySW** [comment]
https://github.com/nanocurrency/raiblocks/pull/999 should be better solution

**Comment by rkeene** [comment]
Can I close this PR in preference to #999 ?

**Pull request closed without merging**
