### PR TITLE
Add http keep alive for RPC callback. Fixes #1125

### LINKED ISSUE #1125: Update HTTP Callback to Support HTTP keep-alive
Currently the HTTP callback mechanism does not use HTTP "Connection: keep-alive"

After moving it to a plugin (#1096), look at adding support for keep-alive to improve performance.

### PR DESCRIPTION
**Pull request by CathalT**
Assuming this is what https://github.com/nanocurrency/raiblocks/issues/1125 is referring to?

Not sure on the actual timeout value itself, should I make it configurable?

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Not quite, the keepalive needed is at the HTTP level, not the TCP level as this PR sets.

**Comment by CathalT** [comment]
2nd part is the http keep alive or am I in the wrong place altogether? 

```
req->insert (boost::beast::http::field::connection, "keep-alive");
req->insert (boost::beast::http::field::keep_alive, "timeout=120");
```

**Comment by cryptocode** [comment]
The callback isn't a persistent connection, it makes a new connection on every observed block.

**Comment by PlasmaPower** [comment]
That tells the server that we support HTTP keepalive, except we don't, which would cause problems with servers that actually support HTTP keepalive.

**Comment by CathalT** [comment]
Ahhh I get you, was looking for a quick issue from the list to get my feet wet, I guess this is not one :smiley:

**Pull request closed without merging**
