### PR TITLE
Prevent RPC double write results with optional errors

### PR DESCRIPTION
**Pull request by SergiySW**

### CODE REVIEW

**Comment by PlasmaPower** [comment]
IIRC `block_create` has a double error write when the wallet is locked.

**Comment by SergiySW** [comment]
This is not single possible location. Now each optional error_response is followed by return; to exit function

**Comment by PlasmaPower** [comment]
I think we've been trying to avoid `return` throughout the codebase.

**Comment by SergiySW** [comment]
It's much simpler to read than https://github.com/nanocurrency/raiblocks/pull/729/files
What is the reason to avoid return; in void functions?

**Comment by PlasmaPower** [comment]
Colin started the convention throughout the codebase. I think it's to preserve control flow from the start to the end of the function.

**Comment by SergiySW** [comment]
In this case there is https://github.com/nanocurrency/raiblocks/pull/729 but it's heavier to read IMO

**Comment by cryptocode** [comment]
This problem is one example where I think we should be using function-localized exceptions. Just a single `response (...)` in the try block, throw string on error, and a single `error_response (err)` in the catch.

**Comment by cryptocode** [comment]
It was suggested that we use RPC to get std::error_code/std::unexpected tested, https://github.com/nanocurrency/raiblocks/pull/769

**Comment by SergiySW** [comment]
Replaced with https://github.com/nanocurrency/raiblocks/pull/970

**Pull request closed without merging**
