### PR TITLE
List of rolled back blocks in block_processor

### PR DESCRIPTION
**Pull request by SergiySW**

### CODE REVIEW

**Comment by clemahieu** [comment]
We can't filter out blocks that have been forced out because the winner can oscillate before quorum.

**Comment by SergiySW** [comment]
If winner will be changed before quorum it will be placed in forced deque, not regular blocks. So ongoing election won't be affected, only fresh bootstrap blocks cannot start same election again & again

**Comment by clemahieu** [comment]
That makes sense.  So this is to prevent the same block from starting an election if it's already failed once. Should add every hash that's not the winner at the end of an election in to this set? We need to consider how big we should allow this container to get and when we want to prune it.

**Comment by SergiySW** [comment]
No significant bootstrap speed improvements, proposed to close

**Comment by rkeene** [comment]
We addressed this in other ways, closing this out.

**Pull request closed without merging**
