### PR TITLE
Fix typo, quorom -> quorum

### PR DESCRIPTION
**Pull request by meltingice**
Noticed a typo not only in the code, but also in the node `config.json`. Not the end of the world, but don't want this to trip someone up later due to inconsistency.

### CODE REVIEW

**Comment by clemahieu** [comment]
Hah, terrible.

We’ll have to do a config file upgrade to support the text change.

**Comment by meltingice** [comment]
Oh yeah, good call. Added the config upgrade. My C++ is a little, uh, rusty... so you'll want to double check the code 😅

**Comment by PlasmaPower** [comment]
I think that currently this will reset the value on upgrade (though I'm not sure because I'm on mobile right now). If that's the case, you should read the old value and use that for the new one.

**Comment by meltingice** [comment]
Nah I read the old value during the upgrade and use it for the new JSON key.

**Comment by meltingice** [comment]
@cryptocode good to know, wasn't sure. I saw it being done elsewhere so I just followed convention.

**Pull request closed without merging**
