### PR TITLE
 Allow OpenSSL 1.1

### PR DESCRIPTION
**Pull request by SergiySW**
Tested with Debian Stretch OpenSSL 1.1.0f

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Does this also work with OpenSSL 1.0?

**Comment by cryptocode** [comment]
The EXACT flag makes sure the LTS (1.0.2x) version of openssl is pulled in if multiple versions are installed, but that may be too conservative if this is a backwards compatible change.

**Comment by SergiySW** [comment]
@PlasmaPower at least working with OpenSSL 1.0.2g (Ubuntu 16.04 LTS)

**Comment by SergiySW** [comment]
1.1.1 also should become LTS
https://www.openssl.org/blog/blog/2018/05/18/new-lts/

**Pull request merged**
