### PR TITLE
 block_balance DB table (draft)

### PR DESCRIPTION
**Pull request by SergiySW**
to improve I/O of balance/amount visitors

data.ldb size
Before: 5302931456
After:    5699977216

### CODE REVIEW

**Comment by clemahieu** [comment]
Can we put the balance in the value of the block table? hash -> [block_data, balance]

Then we don’t need a separate table and it should pack more efficiently.

**Comment by SergiySW** [comment]
make receive_v1, open_v1, change_v1 tables?

**Comment by clemahieu** [comment]
We could detect the length. If len = [block_data] it needs update. If len = [block_data, balance] no update needed.

**Comment by rkeene** [comment]
This will tie into the change to store block confirmation height (#1303), which has been moved to V18.0

**Comment by SergiySW** [comment]
Tied with DB changes in https://github.com/nanocurrency/raiblocks/pull/1303

**Comment by SergiySW** [comment]
@zhyatt

**Comment by SergiySW** [comment]
Closing in favor of https://github.com/nanocurrency/raiblocks/tree/block_sideband

**Pull request closed without merging**
