### PR TITLE
Retry failed core test a few times for 90 days until we can find and …

### PR DESCRIPTION
**Pull request by rkeene**
…fix flakey tests

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Travis runs are already close to the time limit of 50 minutes. I'm afraid that this may push it over that limit.

**Comment by PlasmaPower** [comment]
Per platform

**Comment by PlasmaPower** [comment]
I guess some previous PRs have shortened the builds, so this should work. :+1:

**Comment by rkeene** [comment]
Rebased against master after pull request #1222

**Pull request merged**
