### PR TITLE
Batch signatures verification

### PR DESCRIPTION
**Pull request by SergiySW**

### CODE REVIEW

**Comment by SergiySW** [comment]
On test VM (Core i7 4790K, 8GB RAM, SSD CRUCIAL M500) debug_profile_process results
Without modifications: 148s
With batches: 45s

Of course it's just syntchetic test

**Comment by androm3da** [comment]
Can you squash these into fewer commits, or one if that makes sense?

**Comment by androm3da** [comment]
Can you rebase these changes on `master`?

**Comment by SergiySW** [comment]
I guess better wait till recent block changes

**Comment by androm3da** [comment]
I'm going to close this for now, we can reopen it once you rebase.

**Pull request closed without merging**
