### PR TITLE
Increase minimum protocol version to when epoch blocks were introduced (V15.2)

### PR DESCRIPTION
**Pull request by PlasmaPower**

### CODE REVIEW

**Comment by PlasmaPower** [comment]
I guess this removes legacy peers, so we can get rid of that code.

**Comment by PlasmaPower** [comment]
Done

**Comment by rkeene** [comment]
We'll still have legacy peers in the future, just a different legacy -- some of those tests should probably stay but with a variable version number (probably the minimum we'll peer with ?  I think legacy has a more specific check)

**Comment by PlasmaPower** [comment]
The term legacy in peer_container refers to peers which do not support node id.

**Pull request merged**
