### PR TITLE
Message header extensions: remove unused flags

### PR DESCRIPTION
**Pull request by catenocrypt**
Issue #1196

### CODE REVIEW

**Comment by catenocrypt** [comment]
BI build failed, but there is only one timeout error (node.vote_republish)

**Comment by PlasmaPower** [comment]
I'd prefer to keep query/response local to node ID messages

**Comment by catenocrypt** [comment]
I understand that the query/response flags are used only by the handshake message type, but I suggest to put the flag definition into the central message part, because if a new flag is defined in the general part for all messages, it can conflict with message-type-specific flags.  That's why I think it's better to have all flag definitions in one place  (OK, I know that there are not too many flags definitions).

**Comment by PlasmaPower** [comment]
However, there can be conflicts between different types of messages, and that's fine. E.g. there already are some between node id handshake and bulk pull account.

**Comment by catenocrypt** [comment]
As suggested, I have left query/response flag definitions where they were.

**Pull request merged**
