### PR TITLE
Logging confirm req block hash

### PR DESCRIPTION
**Pull request by SergiySW**

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Any specific reason for this?

**Comment by SergiySW** [comment]
Tracking why sometime pending blocks cannot be auto-received by node.
And this message is useless without info what block node is trying to confirm.

**Comment by PlasmaPower** [comment]
Okay. If you were running the hash2 changes before #603 and #604 were merged, your database probably has bad data, which could be causing problems.

**Comment by SergiySW** [comment]
It doesn't depend on hash2

**Comment by SergiySW** [comment]
in https://github.com/nanocurrency/raiblocks/pull/711

**Pull request closed without merging**
